### ISSUE TITLE
How do you compute hash of user data?

### ISSUE THREAD

**Issue by tanmaybhardwaj** [rudrakh97/KYC-chain#3]
Hi,
From the solidity code kyc.sol, I can see that inside struct 'Customer' user information is stored as a hash.  But I cannot see piece of logic wherein this hash is computed and then stored to this struct. Can you please help to highlight the relevant piece of code which performs this action? 

Best Regards

**Comment by rudrakhp** [comment]
For the trial run, we had passed the complete user information as a single string as of now. But we can also use the RSA encryption protocol provided in the file `RSA_JS` by calling the encryption function (see PS) from this file. Since the trial run had smaller strings to store, to avoid complications, we had removed the `RSA` encryption part. 
PS: Refer to `RSAEncrypt()` in [this](https://github.com/rudrakh97/KYC-chain/blob/master/root/RSA_JS/rsa.js) file.
